# Generated by Django 3.1.5 on 2021-02-15 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_Name', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('Contact_Person1', models.CharField(max_length=100)),
                ('Contact_Person2', models.CharField(blank=True, max_length=100)),
                ('Contact1', models.IntegerField(blank=True)),
                ('Contact2', models.IntegerField(blank=True)),
                ('Contact3', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='OEM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OEM_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_Name', models.CharField(max_length=50)),
                ('Contact_Number', models.IntegerField()),
                ('Customer_Location', models.TextField()),
                ('Product_Part_Number', models.CharField(max_length=50)),
                ('Serial_Pak_Number', models.CharField(max_length=50)),
                ('Refrence_Service_Part_Number', models.CharField(max_length=50)),
                ('PO_Number', models.CharField(max_length=50)),
                ('SO_Number', models.CharField(max_length=50)),
                ('COP_Number', models.CharField(max_length=50)),
                ('Contract_Number', models.CharField(max_length=50)),
                ('Quote_Number', models.CharField(max_length=50)),
                ('Start_Date', models.CharField(max_length=50)),
                ('End_Date', models.CharField(max_length=50)),
                ('Remark', models.TextField()),
                ('AMC', models.CharField(choices=[('contract', 'Contract'), ('CTPL', 'CTPL'), ('both', 'BOTH')], default=None, max_length=50)),
                ('License_PartID', models.CharField(max_length=50)),
                ('License_OrderNo', models.CharField(max_length=50)),
                ('License_SO', models.CharField(max_length=50)),
                ('License_PAK', models.CharField(max_length=50)),
                ('License_Description', models.TextField()),
                ('License_Quantity', models.IntegerField()),
                ('License_Start_Date', models.CharField(max_length=50)),
                ('License_End_Date', models.CharField(max_length=50)),
                ('License_Remark', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_Name', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('Start_Date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IR_Name', models.CharField(max_length=100)),
                ('Date_Created', models.DateField(auto_now_add=True)),
                ('Date_Modified', models.DateField(auto_now=True)),
                ('Remark', models.TextField()),
                ('Upload_IR', models.FileField(upload_to='IR/files/')),
                ('Company_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.company')),
                ('OEM_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.oem')),
                ('Project_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.project')),
            ],
        ),
        migrations.CreateModel(
            name='DC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DC_Name', models.CharField(max_length=100)),
                ('Date_Created', models.DateField(auto_now_add=True)),
                ('Date_Modified', models.DateField(auto_now=True)),
                ('Remark', models.TextField()),
                ('Upload_DC', models.FileField(upload_to='DC/files/')),
                ('Company_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.company')),
                ('OEM_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.oem')),
                ('Project_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.project')),
            ],
        ),
        migrations.CreateModel(
            name='COP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COP_Name', models.CharField(max_length=100)),
                ('Date_Created', models.DateField(auto_now_add=True)),
                ('Date_Modified', models.DateField(auto_now=True)),
                ('Remark', models.TextField()),
                ('Upload_COP', models.FileField(upload_to='COP/files/')),
                ('Company_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.company')),
                ('OEM_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.oem')),
                ('Project_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.project')),
            ],
        ),
        migrations.CreateModel(
            name='BOQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BOQ_Name', models.CharField(max_length=100)),
                ('Date_Created', models.DateField(auto_now_add=True)),
                ('Date_Modified', models.DateField(auto_now=True)),
                ('Remark', models.TextField()),
                ('Upload_BOQ', models.FileField(upload_to='BOQ/files/')),
                ('Company_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.company')),
                ('OEM_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.oem')),
                ('Project_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.project')),
            ],
        ),
    ]
