# Generated by Django 3.1.5 on 2021-02-18 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210215_1142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cop',
            old_name='Company_Name',
            new_name='Company',
        ),
    ]
