# Generated by Django 3.1.5 on 2021-02-25 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210219_0116'),
    ]

    operations = [
        migrations.CreateModel(
            name='RMA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sr_No', models.IntegerField()),
                ('Call_Time_CMD', models.CharField(max_length=20)),
                ('Call_Log_Date', models.CharField(max_length=20)),
                ('RMA_Raised_Time', models.CharField(max_length=20)),
                ('SR_Number', models.IntegerField()),
                ('RMA_Number', models.IntegerField()),
                ('Customer_name', models.CharField(max_length=30)),
                ('Location_name', models.CharField(max_length=30)),
                ('Contact_Name', models.CharField(max_length=30)),
                ('Contact_Details', models.IntegerField()),
                ('Faulty_Part_Type', models.CharField(max_length=30)),
                ('Faulty_Part_make_and_Model', models.CharField(max_length=30)),
                ('Faulty_Router_Serial', models.CharField(max_length=30)),
                ('RMA_Make_and_Modem', models.CharField(max_length=30)),
                ('RMA_Serial_Number', models.CharField(max_length=30)),
                ('Fault_Logged_discription', models.CharField(max_length=30)),
                ('Troubleshootings', models.CharField(max_length=30)),
                ('RMA_Approved_Date', models.CharField(max_length=30)),
                ('RMA_Received_CTPL', models.CharField(max_length=30)),
                ('RMA_Delivered_Date', models.CharField(max_length=30)),
                ('Faulty_Part_replacement_status_Pickup_Done_or_Not', models.CharField(max_length=30)),
                ('Faulty_Part_pick_up_Date', models.CharField(max_length=30)),
                ('Faulty_Part_pick_up_Time', models.CharField(max_length=30)),
                ('Remark', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='RMA_Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sr_No', models.IntegerField()),
                ('Remark', models.CharField(max_length=30)),
                ('Old_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.rma')),
            ],
        ),
    ]
